// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKa-8MJdmEVisCrVvkx3EGPPdxhuPomU',
    appId: '1:875446474727:web:4f8536d785c0aebf008f42',
    messagingSenderId: '875446474727',
    projectId: 'son-mobil-proje-yusuf',
    authDomain: 'son-mobil-proje-yusuf.firebaseapp.com',
    storageBucket: 'son-mobil-proje-yusuf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKreo5e8kc8vefef1wrncIQ1Wgs9ssMPw',
    appId: '1:875446474727:android:63e5655043e062f4008f42',
    messagingSenderId: '875446474727',
    projectId: 'son-mobil-proje-yusuf',
    storageBucket: 'son-mobil-proje-yusuf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhOu78CvWZcNG2GjaJSFxJHRpWN-ZjeA',
    appId: '1:875446474727:ios:fe17a2bc1ed241f8008f42',
    messagingSenderId: '875446474727',
    projectId: 'son-mobil-proje-yusuf',
    storageBucket: 'son-mobil-proje-yusuf.appspot.com',
    iosClientId: '875446474727-kaco74i546q46pbos73sieamth1hki1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballapp2',
  );
}
